### ISSUE TITLE
Gateway list request error

### ISSUE THREAD

**Issue by kf4mot** [km4ack/Pat-Menu#21]
Pi3 running Buster. When I run it I get this error message:

`Gateway List Request

1) ARDOP List
2) Packet List
3) Main Menu
Please enter your choice: 1
touch: cannot touch '/home/pi/.wl2k/mailbox/kf4mot/out/GUTZ7GLWM2QZ.b2f': No such file or directory
/home/pi/patmenu/catalog: line 43: /home/pi/.wl2k/mailbox/kf4mot/out/GUTZ7GLWM2QZ.b2f: No such file or directory
/home/pi/patmenu/catalog: line 44: /home/pi/.wl2k/mailbox/kf4mot/out/GUTZ7GLWM2QZ.b2f: No such file or directory
/home/pi/patmenu/catalog: line 45: /home/pi/.wl2k/mailbox/kf4mot/out/GUTZ7GLWM2QZ.b2f: No such file or directory
/home/pi/patmenu/catalog: line 46: /home/pi/.wl2k/mailbox/kf4mot/out/GUTZ7GLWM2QZ.b2f: No such file or directory
/home/pi/patmenu/catalog: line 47: /home/pi/.wl2k/mailbox/kf4mot/out/GUTZ7GLWM2QZ.b2f: No such file or directory
/home/pi/patmenu/catalog: line 48: /home/pi/.wl2k/mailbox/kf4mot/out/GUTZ7GLWM2QZ.b2f: No such file or directory
/home/pi/patmenu/catalog: line 49: /home/pi/.wl2k/mailbox/kf4mot/out/GUTZ7GLWM2QZ.b2f: No such file or directory
/home/pi/patmenu/catalog: line 50: /home/pi/.wl2k/mailbox/kf4mot/out/GUTZ7GLWM2QZ.b2f: No such file or directory
/home/pi/patmenu/catalog: line 51: /home/pi/.wl2k/mailbox/kf4mot/out/GUTZ7GLWM2QZ.b2f: No such file or directory
/home/pi/patmenu/catalog: line 52: /home/pi/.wl2k/mailbox/kf4mot/out/GUTZ7GLWM2QZ.b2f: No such file or directory
/home/pi/patmenu/catalog: line 53: /home/pi/.wl2k/mailbox/kf4mot/out/GUTZ7GLWM2QZ.b2f: No such file or directory
/home/pi/patmenu/catalog: line 54: /home/pi/.wl2k/mailbox/kf4mot/out/GUTZ7GLWM2QZ.b2f: No such file or directory
Your request has been posted to the outbox of Pat Winlink
Please go to Pat and initiate a connection to send the request
Press any key to continue`

Looking for these locations on my system I can see that they don't exist.

**Comment by km4ack** [comment]
call sign should be all caps. this is an issue within the code.

**Comment by km4ack** [comment]
resolved v0.56
