### ISSUE TITLE
Patmenu download locks up the file viewer

### ISSUE THREAD

**Issue by 1cheapmike** [km4ack/Pat-Menu#22]
Downloaded the github pat menu and let it run.  When trying to go to the next step of viewing config file the file browser flashes open and immediately closes. Same results after rebooting and doing update/upgrade seperately.

Mike Ring
KE0LCK

**Comment by km4ack** [comment]
This issue is a known issue with Buster. Run sudo 'apt -y full-upgrade' to resolve.

**Comment by 1cheapmike** [comment]
Jason,
Thanks for the assist.  Got it working now!
Mike Ring
KE0LCK
