### ISSUE TITLE
Packet Connections/mode 

### ISSUE THREAD

**Issue by kd5pqj** [km4ack/Pat-Menu#27]
Did not find a way to switch between the Signal Link USB/Direwolf to MobiLink TNC BlueTooth to Draws/direwolf?
Did not find a way to switch between 1200/9600 APRS or maybe a VARA FM modem instead of Direwolf modem.

**Comment by km4ack** [comment]
VARA not compatible with Linux. Opened another issue to add support for mobilinkd TNC https://github.com/km4ack/patmenu/issues/29
